### ISSUE TITLE
Does the potions still drop?

### ISSUE THREAD

**Issue by Tanjiraaaaa** [litetex-oss/mcm-raid-restore#57]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/litetex-oss/mcm-raid-restore/issues) or [closed](https://github.com/litetex-oss/mcm-raid-restore/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

My question is if the bad omen potions still dropped as loot from the captains

**Comment by litetex** [comment]
Since the loot was not modified in any way you should get the same drops as when running the game without the mod.

According to the wiki:
> [Ominous bottles are dropped by raid captains outside of raids, at a random level from 1-5.](https://minecraft.wiki/w/Ominous_Bottle#Mob_loot)

Note however that in stacked raid farms it is possible for raid captains to leave a raid (since raids are constantly spawned and broken) which then results in them dropping a Ominous bottle.

Hope this helps :)
